B"""Doctest for 3-say_my_name.py"""


>>> say_my_name = __import__('3-say_my_name').say_my_name


"""Edge cases"""


>>> say_my_name('Eduardo', 9)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(9, 'Eduardo')
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name()
Traceback (most recent call last):
TypeError: say_my_name() missing 1 required positional argument: 'first_name'

>>> say_my_name([123], [98, 87])
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo")
My name is Eduardo 

>>> say_my_name('Eduardo')
My name is Eduardo 

>>> class Eduardo:
...     pass

>>> say_my_name(Eduardo)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(x)
Traceback (most recent call last):
NameError: name 'x' is not defined

>>> say_my_name("Eduardo", x)
Traceback (most recent call last):
NameError: name 'x' is not defined

>>> say_my_name(x, "Eduardo")
Traceback (most recent call last):
NameError: name 'x' is not defined

>>> say_my_name(True)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo", False)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo")
My name is Eduardo 

>>> say_my_name(float('inf'))
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(float('nan'))
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("")
My name is  

>>> say_my_name(x, y)
Traceback (most recent call last):
NameError: name 'x' is not defined

>>> say_my_name(["Eduardo"], "Vega")
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(None)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(None, "Eduardo")
Traceback (most recent call last):
TypeError: first_name must be a string


>>> say_my_name("Eduardo", "Vega")
My name is Eduardo Vega

>>> say_my_name("Eduardo, (1,2,3))
Traceback (most recent call last):
SyntaxError: EOL while scanning string literal

>>> say_my_name((1,2,3), "Vega")
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name([1,2], "Vega")
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo", [1,2])
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name({eduardo: vega}, "Vega")
Traceback (most recent call last):
NameError: name 'vega' is not defined

>>> say_my_name("Eduardo", {eduardo: vega})
Traceback (most recent call last):
NameError: name 'vega' is not defined

>>> say_my_name((1, 2, 3), (1, 2, 3))
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(1, 2)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name({eduardo: vega})
Traceback (most recent call last):
NameError: name 'vega' is not defined

>>> say_my_name([1,2])
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name((1,2))
Traceback (most recent call last):
TypeError: first_name must be a string

>>> def sum(a, b):
...     pass

>>> say_my_name(sum)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo", sum)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name(sum, "Vega")
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name('Eduardo', 'Vega')
My name is Eduardo Vega

>>> say_my_name('Eduardo', "Vega")
My name is Eduardo Vega

>>> say_my_name("Eduardo", 'Vega')
My name is Eduardo Vega

>>> say_my_name("Eduardo", "Vega")
My name is Eduardo Vega

>>> say_my_name(5j)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo", 5j)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("5j")
My name is 5j 

>>> say_my_name(None, None)
Traceback (most recent call last):
TypeError: first_name must be a string

>>> say_my_name("Eduardo", "A", "Vega")
Traceback (most recent call last):
TypeError: say_my_name() takes from 1 to 2 positional arguments but 3 were given

>>> say_my_name(("Hola, "mundo"), "Vega")
Traceback (most recent call last):
SyntaxError: invalid syntax

>>> say_my_name("Vega", ("Hola, "mundo"))
Traceback (most recent call last):
SyntaxError: invalid syntax

>>> say_my_name(["Eduardo, "Vega"], "Vega")
Traceback (most recent call last):
SyntaxError: invalid syntax
